return {
  --{
  --  "EdenEast/nightfox.nvim",
  --  lazy = false, -- make sure we load this during startup if it is your main colorscheme
  --  priority = 1000, -- make sure to load this before all the other start plugins
  --  config = function()
  --    -- load the colorscheme here
  --    vim.cmd("colorscheme nightfox")
  --  end,
  --},
  --{
  --  "folke/tokyonight.nvim",
  --  lazy = false,
  --  priority = 1000,
  --  config = function()
  --    vim.cmd([[colorscheme tokyonight]])
  --  end,
  --},
  --{
  --  "rebelot/kanagawa.nvim",
  --  lazy = false,
  --  priority = 1000,
  --  config = function()
  --    vim.cmd.colorscheme("kanagawa")
  --    --vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
  --    --vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
  --  end,
  --},
  --{
  --  "AlphaTechnolog/pywal.nvim",
  --  as = "pywal",
  --  config = function()
  --    require("pywal").setup()
  --  end,
  --},

}
